version: '3'

services:
  roma-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=R0maR00tPassw0rd
      - MYSQL_DATABASE=simulation
      - MYSQL_USER=simulation
      - MYSQL_PASSWORD=Simulati0n
    volumes:
     - "mysql-data:/var/lib/mysql"

  roma-server:
    image: roma/roma-server
    ports:
      - "8084:8080"
    depends_on:
      - roma-mysql

  pangaea-servlet:
    image: roma/pangaea-servlet
    ports:
      - "8085:8080"


volumes:
  mysql-data:
